---
- name: test
  hosts: all
  become: yes

  tasks:
    - name: install apache2 package
      apt: name=apache2 state=latest
    - name: Start Apache
      service: name=apache2 state=started enabled=yes