FROM node:12-alpine as build
WORKDIR /app
COPY /front/package*.json /app/package.json
RUN npm install
COPY /front /app
RUN npm run build

FROM nginx:1.21.5-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY /conf/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]